// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "htmlparser/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// PgRepoInterface is an autogenerated mock type for the PgRepoInterface type
type PgRepoInterface struct {
	mock.Mock
}

// AddParsing provides a mock function with given fields: _a0, _a1, _a2
func (_m *PgRepoInterface) AddParsing(_a0 context.Context, _a1 string, _a2 string) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for AddParsing")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetParsing provides a mock function with given fields: _a0, _a1
func (_m *PgRepoInterface) GetParsing(_a0 context.Context, _a1 string) (entity.Parsing, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetParsing")
	}

	var r0 entity.Parsing
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entity.Parsing, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entity.Parsing); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(entity.Parsing)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPgRepoInterface creates a new instance of PgRepoInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPgRepoInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *PgRepoInterface {
	mock := &PgRepoInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
